config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  get 'passwords/new'

  root to: "site#index"

  # get "/search",    to: "site#search", as: "search"

  get "/login",     to: "session#new"

  post "/login",    to: "session#create"

  delete "/logout", to: "session#destroy"

  get "/logout",    to: "session#destroy" #TO DO: delete this before production

  get "/signup",    to: "users#new"

  # this might not be necessary
  get "/rentals",   to: "rentals#index", as: "browse"
  get "/rentals",   to: "rentals#index", as: "rentals"
  get "/about",     to: "site#about", as: "about"

  get "/contact",   to: "site#contact", as: "contact"

  post "/users/:user_id/rentals/:rental_id/reviews",  to: "reviews#create"

  post "/password/:id", to: "passwords#update"

  resources :search

  resources :users do
      resources :reviews
      resources :rentals
  end

  resources :rentals do
    resources :agreements
  end

  resources :passwords

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    #login form
    if session[:user_id] != nil
      redirect_to root_path
    end
  end

  def create
    #where auth happens
    @user = User.authenticate(params[:user][:email], params[:user][:password])

    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:notice] = "There was a problem with your email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:logged_out] = "You're logged out."
    redirect_to login_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<%= render partial: "site/nav", locals: { user: @user } %>

<div class="row">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <h1>Login</h1>

    <!-- flash message -->
    <% flash.each do |k, v|%>
      <p id="<%= k %>"><%= v %></p>
    <% end %>

      <!-- LOGIN FORM -->
      <%= form_for :user do |f| %>
          <div class="form-group">
            <%= f.label :email  %>:
            <%= f.text_field :email, class: "form-control", placeholder: "Enter your email" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>:
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
          </div>
          <div class="form-group">
            <%= f.submit "Login", class: "form-control btn btn-danger"%>
          </div>
      <% end %>

      <%= link_to ">> Make an account", signup_path %>
      <%= link_to ">> Forgot Password?", new_password_path %>

  </div>
</div>