config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  get 'passwords/new'

  root to: "site#index"

  # get "/search",    to: "site#search", as: "search"

  get "/login",     to: "session#new"

  post "/login",    to: "session#create"

  delete "/logout", to: "session#destroy"

  get "/logout",    to: "session#destroy" #TO DO: delete this before production

  get "/signup",    to: "users#new"

  # this might not be necessary
  get "/rentals",   to: "rentals#index", as: "browse"
  get "/rentals",   to: "rentals#index", as: "rentals"
  get "/about",     to: "site#about", as: "about"

  get "/contact",   to: "site#contact", as: "contact"

  post "/users/:user_id/rentals/:rental_id/reviews",  to: "reviews#create"

  post "/password/:id", to: "passwords#update"

  resources :search

  resources :users do
      resources :reviews
      resources :rentals
  end

  resources :rentals do
    resources :agreements
  end

  resources :passwords

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :rentals, dependent: :destroy
	has_many :reviews, as: :reviewable, dependent: :destroy
	has_many :agreements, dependent: :destroy

	validates :email,
		:presence => {:message=> 'Field cannot be left blank'},
		:uniqueness => true,
		:format => {:with => /\A[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})\z/}

	validates :password_digest,
		:presence => {:message=> 'Field cannot be left blank'},
		:confirmation => true,
		:length => { minimum: 6 }, on: :create

	validates :first_name,
		:presence => {:message=> 'Field cannot be left blank'}



	validates :last_name,
		:presence => {:message=> 'Field cannot be left blank'}


	# validates :isOwner,
	# 	:inclusion => {:in => [true, false]}

	#add more specifics for location
	# validates :location,
	# 	:presence =>true


	def set_password_reset
	  self.code = SecureRandom.urlsafe_base64
	  self.expires_at = 4.hours.from_now
	  self.save!
	end

	def self.authenticate email, password
		User.find_by_email(email).try(:authenticate, password)
	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@users = User.all
  end

  def new
  	@user = User.new

  end

  def create
  	new_user = params.require(:user).permit(
  		:first_name,
  		:last_name,
  		:email,
  		:password,
  		:image_url,
  		:isOwner,
  		:location)
  	@user = User.create(new_user)

    if @user.valid?
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render new_user_path
    end


  end

  def edit
    user_id = params[:id]
    @user = User.find_by_id(user_id)
  end

  def update
    if session[:user_id] == nil
      redirect_to root_path
    else
      @current_user = User.find_by_id(session[:user_id])
    end
    user_id = params[:id]
    res = params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :image_url)
    user = User.find_by_id(user_id)

    user.update_attributes(
      :first_name => res[:first_name],
      :last_name  => res[:last_name],
      :email      => res[:email],
      :image_url  => res[:image_url])
    redirect_to "/users/#{user_id}"
  end

  def show
    user_id = params[:id]
    @user = User.find_by_id(user_id)

    @user_reviews = @user.reviews || []
    @new_user_review = @user.reviews.new


    #find user for nav bar
    @current_user = current_user

    # will pull all the owners agreements from the agreement table
    rental_ids = @user.rentals.map(&:id)
    @owners_agreements = Agreement.where(rental_id: rental_ids)


    @owners_denied_agreements = Agreement.where(rental_id: rental_ids, approved: false)
    @owners_pending_agreements = Agreement.where(rental_id: rental_ids, approved: nil)
    @owners_approved_agreements = Agreement.where(rental_id: rental_ids, approved: true)

    # anyone who has put in a request (in the agreement table)
    @renters_agreements = Agreement.where(user_id: @current_user)
    @renters_denied_agreements = Agreement.where(user_id: @current_user, approved: false)
    @renters_approved_agreements = Agreement.where(user_id: @current_user, approved: true)
    @renters_pending_agreements = Agreement.where(user_id: @current_user, approved: nil)

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 <div class="row">
  <div class="col-xs-8 col-sm-4"></div>
  <div class="col-xs-8 col-sm-4 col-offset-4">

    <h1>Edit your account</h1>

    <!-- new user form -->
    <%= form_for @user do |f| %>
  		<div class="form-group">
	  		<%= f.label :first_name %>:
	  		<%= f.text_field :first_name, class: "form-control", :autofocus => true %>
  		</div>

  		<div class="form-group">
	  		<%= f.label :last_name %>:
	  		<%= f.text_field :last_name, class: "form-control" %>
  		</div>

  		<div class="form-group">
	  		<%= f.label :email %>:
	  		<%= f.email_field :email, class: "form-control" %>
  		</div>

  		<div class="form-group">
	  		<%= f.label :image_url %>:
	  		<%= f.text_field :image_url, class: "form-control" %>
  		</div>

  		<div class="form-group">
	  		<%= f.submit "Update User", class: "form-control btn btn-danger" %>
  		</div>

      <nav>
        <div class="btn btn-default">
          <a href="/">Root</a>
        </div>
        <div class="btn btn-default">
          <a href="/users/new">Sign-up</a>
        </div>
        <div class="btn btn-default">
           <a href="/login">Login</a>
        </div>
        <div class="btn btn-default">
          <a href="/rentals">Rentals Index</a>
        </div>
        <div class="btn btn-default">
          <a href="<%= new_user_rental_path(@user.id) %>">Rentals New</a>
        </div>
      </nav>
  	<% end %>
  </div>
  <div class="col-xs-8 col-sm-4 col-offset-4">
</div>

app/views/users/new.html.erb
<%= render partial: "site/nav", locals: { user: @user } %>

 <div class="row">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">

    <h1>Sign-up</h1>

    <!-- Validation error messages -->
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <% @user.errors.full_messages.each do |msg| %>
              <p><%= msg %></p>
            <% end %>
          </div>
        <% end %>

    <!-- new user form -->
    <%= form_for @user do |f| %>
  		<div class="form-group">
	  		<%= f.label :first_name %>
	  		<%= f.text_field :first_name, class: "form-control", :autofocus => true %>

  		</div>

  		<div class="form-group">
	  		<%= f.label :last_name %>
	  		<%= f.text_field :last_name, class: "form-control" %>

  		</div>

  		<div class="form-group">
	  		<%= f.label :email %>
	  		<%= f.email_field :email, class: "form-control" %>
  		</div>

  		<div class="form-group">
	  		<%= f.label :password %>
	  		<%= f.password_field :password, class: "form-control" %>
  		</div>

  		<div class="form-group">
	  		<%= f.label :image_url %>
	  		<%= f.text_field :image_url, class: "form-control" %>
  		</div>

  		<div class="form-group">
	  		<%= f.submit "Create User", class: "form-control btn btn-danger" %>
  		</div>
  	<% end %>

  </div>
</div>

app/views/users/show.html.erb
<%= render partial: "site/nav", locals: { user: @user }  %>

<!-- ROW 1 of 3 -->
<div class="row" id="welcome">
  <div class="col-xs-12 col-sm-1 col-offset-1">
    <!-- USER IMAGE -->
    <img src="<%= @user.image_url %>" id="user-image">
  </div>

  <div class="col-sm-6 col-sm-offset-1">
    <!-- WELCOME MESSAGE -->
    <% if @current_user == @user %>
      <h3>Hello, <%= @current_user.first_name %> <%= @current_user.last_name %>!</h3>

        <!-- flash message -->
        <% flash.each do |k, v|%>
          <p style="color: green" id="<%= k %>"><%= v %></p>
        <% end %>

         <!-- EDIT PROFILE BUTTON -->
         <div class="col-sm-1 col-sm-offset-12">
           <button class="btn btn-danger btn-sm" id="profile-edit">Edit Profile</button>
         </div>

    <% else %>
      <h3><%= @user.first_name %> <%= @user.last_name %></h3>
   <% end %>
  </div>
</div>


<!-- BREAKING UP PAGE FOR COOL COLORS -->
<div class="rest-of-page">

<!-- ROW 2 of 3 -->
<!-- HIDES ALL TO NON-CURRENT USERS -->
<% if @current_user == @user %>
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-1">

      <!-- CURRENT LISTINGS -->
      <div class="user-listing">
        <p><strong>Your current listings:</strong></p>
        <% @user.rentals.each do |rental| %>
          <div class="my-listings">
            <a href="/users/<%= @current_user.id %>/rentals/<%= rental.id %>"><p><%= rental.title %></p></a>
            <p> <%= rental.description %></p>
            <p>Current asking price: $<%= rental.price %>/day</p>
            <!-- CURRENTLY NOT FUNCTIONAL 9/3 8:40pm -->
            <button class="btn btn-danger btn-sm">Edit Listing</button>
          </div>
        <% end %>
      </div>

  <!-- div closing first column  -->
  </div>

    <!-- REVIEWS -->
    <!-- ONLY VISIBLE TO CURRENT USER -->
    <div class="col-sm-5 col-sm-offset-1">
      <div id="your-reviews">
        <h5> <%= @user.reviews.length %> people have reviewed you!</h5>
        <button class="btn btn-primary btn-sm" id="review-show-link">See your reviews</button>
          <div id ="userreview-display-CU">
            <% if @user.reviews.length > 0 %>
              <% @user.reviews.each do |review| %>
                <% if review.description != nil %>
                  <p><%= review.description %></p> <br>
                <% end %>
              <% end %>
            <% end %>
          </div>
      </div>

      <div id="your-updates">

      <!-- PENDING REQUESTS -->
      <div class="pending-requests">
      <% if @owners_agreements.length > 0 %>
        <h5> You have <%= @owners_pending_agreements.length %> pending rental requests </h5>
         <% @owners_pending_agreements.each do |agreement| %>
            <!-- setting variables -->
            <% agreementid = agreement.rental_id %>
            <% rental = Rental.find_by_id(agreementid) %>

            <% renterid = agreement.user_id %>
            <% user = User.find_by_id(renterid) %>

            <!-- REQUESTER INFORMATION -->
            <div class="single-request">
              <p><a href="/users/<%= renterid %>"><%= user.first_name %> <%= user.last_name %></a></p>
              <p>Message:</p>
              <p><%= agreement.rent_date %></p>

              <!-- APPROVAL BUTTONS -->
              <form action="/rentals/<%= agreement.rental_id %>/agreements/<%= agreement.id %>" method="patch" class="approval-form">
                <input type="submit" value="Approve" name="approve" class="btn btn-success btn-sm"></input>
                <input type="submit" value="Decline" name="decline" class="btn btn-danger btn-sm"></input>
              </form>
            </div>
          <!-- end each do block -->
        <% end %>
        <!-- end if @owners_agreements.length -->
      <% end %>
      </div>

      <!-- APPROVED REQUESTS -->
      <div class="upcoming-visits">
        <% if @owners_approved_agreements.length > 0 %>
          <h5>Upcoming Visitors:</h5>
           <% @owners_approved_agreements.each do |agreement| %>
              <!-- setting variables -->
              <% agreementid = agreement.rental_id %>
              <% rental = Rental.find_by_id(agreementid) %>

              <% renterid = agreement.user_id %>
              <% user = User.find_by_id(renterid) %>

              <!-- VISITOR INFORMATION -->
              <div class="single-request">
                <p><a href="/users/<%= renterid %>"><%= user.first_name %> <%= user.last_name %></a></p>
                <p>Details:</p>
                <p><%= agreement.rent_date %></p>
              </div>
            <!-- end each do block -->
          <% end %>
          <!-- end if @owners_agreements.length -->
        <% end %>
      </div>

      <!-- IF RENTER: APPROVED RENTAL REQUESTS -->
      <div class="approved-request">
        <% if @renters_agreements.length > 0 %>
        <% if @renters_approved_agreements.length > 0 %>

          <h5>Your request has been approved! </h5>
          <p>You have upcoming plans for these backyards: </p>
            <% @renters_approved_agreements.each do |agreement| %>
              <!-- setting variables -->
              <% agreementid = agreement.rental_id %>
              <% rental = Rental.find_by_id(agreementid) %>

              <% renterid = agreement.user_id %>
              <% user = User.find_by_id(renterid) %>

              <a href="/users/<%= user.id %>/rentals/<%= rental.id %>"><p><%= rental.title %></p></a>
              <p>Details: </p>
              <p><%= agreement.rent_date %></p>
          <!-- ending renters_approved_agreements each do  -->
          <% end %>
        <!-- ending renters_approved_agreements.length -->
        <%end%>
      </div>


        <!-- IF RENTER: DENIED RENTAL REQUESTS -->
        <div class="denied-request">
          <% if @renters_denied_agreements.length > 0 %>
            <h5>The host of this listing couldn't accommodate you at this time...</h5>

              <% @renters_denied_agreements.each do |agreement| %>
                <!-- setting variables -->
                <% agreementid = agreement.rental_id %>
                <% rental = Rental.find_by_id(agreementid) %>

                <% renterid = agreement.user_id %>
                <% user = User.find_by_id(renterid) %>

                <a href="/users/<%= user.id %>/rentals/<%= rental.id %>"><p><%= rental.title %></p></a>
              <!-- ending each do -->
              <% end %>
          <% end %>
        <!-- ending renters_agreements.length -->
        <% end %>
        </div>
      </div>
    <!-- closing column 2 -->
    </div>
<!-- closing row 2 -->
</div>



<!-- ONLY VISIBLE TO NON-CURRENT USERS -->
<% else %>

    <div class="row">
     <div class="col-sm-5 col-sm-offset-1">
      <!-- RENTAL DISPLAY -->
        <div id="rental-listing">
          <a href="/users/<%= @user.id%>/rentals/<%= @user.rentals[0].id %>"><h3><%= @user.rentals[0].title %></h3></a>
            <h5><strong>About this backyard:</strong></h5>
            <p><%= @user.rentals[0].description %></p>

            <h5><strong>Rent it for a day! </strong></h5>
            <p>$<%= @user.rentals[0].price %></p>

            <img src="<%= @user.rentals[0].image_url %>" id="rental-pic"><br>


        </div>
      </div>

    <div class="col-sm-4 col-sm-offset-1" id="userreview-all">
    <!-- USER REVIEW FORM -->
       <h4> Have you visited <%= @user.first_name %>'s? <a href="javascript:void(0);" id ="userreview-button">Leave a review</a></h4>
          <form id="user-review" action="/users/<%= @user.id %>/reviews" method="post">

              <div class= "form-group">
                <label>Rating (1-5):</label>
                <input type="range" min="1" max="5" step="1" value="1" name="review[rating]" id="rating-val" autofocus/>

                <label>Add a review:</label>
                <textarea class="form-control" rows="5" cols="100" name="review[description]" id="description-val" placeholder="Leave a review"></textarea>
              </div>

                <%= token_tag form_authenticity_token %>

                <input type="submit" value: "Add Review", class="btn btn-danger">
          </form>

        <!-- REVIEWS DISPLAY -->
        <% if @user.reviews.length > 0 %>
          <h5>Reviews (<%= @user.reviews.length %>)</h5>
          <% @user.reviews.each do |review| %>
            <% if review.description != nil %>
              <div id="userreview-display">
                <span><img src="https://cdn1.iconfinder.com/data/icons/humano2/24x24/actions/bookmark-new.png"></span> <%= review.description %><br>
              </div>
            <% end %>
        <% end %>
      <% end %>
    </div>

  <!-- closing row 3 -->
  </div>
<% end %>


</div>